app/models.py
from app.exts import db


class TodoList(db.Model):
    """
    Todo List Model
    """
    __tablename__ = 'todolist'

    id = db.Column(
        db.Integer, primary_key=True)

    name = db.Column(
        db.String(255),
        nullable=False
    )

    def __repr__(self):
        return f'Todo List: {self.name}'


class TodoItem(db.Model):
    """
    Todo List Item Model
    """
    __tablename__ = 'todoitem'

    id = db.Column(
        db.Integer,
        primary_key=True
    )

    task = db.Column(
        db.String(255),
        nullable=False
    )

    isCompleted = db.Column(
        db.Boolean,
        default=False
    )
    todo_list = db.relationship(
        'TodoList',
        backref="tasks"
    )

    todo_list_id = db.Column(db.Integer,
                             db.ForeignKey('todolist.id'))

app/todo_list/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import Length, Required


class TodoForm(FlaskForm):
    task = StringField("Enter your task", validators=[
                       Required(), Length(1, 128)])
    submit = SubmitField("Add new task")


class TodoListForm(FlaskForm):
    name = StringField(
        "Enter your todolist title", validators=[Required(), Length(1, 129)])
    submit = SubmitField("Add")

app/__init__.py
from flask import Flask
from app.exts import db
from app.main.routes import main
from app.todo_list.routes import todoList


def create_app(config_object='config.Config'):
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)

    # register blueprints
    app.register_blueprint(main, url_prefix='')
    app.register_blueprint(todoList, url_prefix='/todolist')
    return app


def register_extensions(app):
    db.init_app(app)
    from app import models
    db.create_all(app=app)

app/main/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.common.service import get_all, delete_one
from app.models import TodoList
from app.todo_list.forms import TodoListForm
from app.exts import db

main = Blueprint('main', __name__, template_folder='templates')


@main.route('/', methods=['GET', 'POST', 'DELETE'])
def index():
    todos = get_all(TodoList)
    form = TodoListForm(request.form)
    if request.method == 'POST':
        todolist = TodoList(name=form.name.data)
        db.session.add(todolist)
        db.session.commit()
        return redirect(url_for('main.index'))

    return render_template('index.html', todos=todos, form=form)


@main.route('/<int:todoid>', methods=['POST'])
def delete_todo(todoid):
    if request.method == 'POST':
        delete_one(TodoList, todoid)
        return redirect(url_for('main.index'))
    return redirect(url_for('todoList.get_todo', todoid=todoid))

app/todo_list/routes.py
from flask import Blueprint, render_template, request, url_for, redirect
from app.common.service import get_one, delete_one
from app.models import TodoList, TodoItem
from app.todo_list.forms import TodoForm
from app import db

todoList = Blueprint('todoList', __name__, template_folder='templates')


@todoList.route('/', methods=['GET'])
def get_todos():
    return redirect(url_for('main.index'))


@todoList.route('/<int:todoid>', methods=['GET', 'POST'])
def get_todo(todoid):
    form = TodoForm(request.form)
    todo = get_one(TodoList, todoid)
    if request.method == 'POST':
        task = form.task.data
        new_item = TodoItem(task=task)
        new_item.todo_list = todo
        db.session.add(new_item)
        db.session.commit()
        return redirect(url_for('todoList.get_todo', todoid=todoid))

    return render_template('todolist.html', todo=todo, form=form)


@todoList.route('<int:todoId>/clearComplete', methods=['POST'])
def clear_todo(todoId):
    todo_list = get_one(TodoList, todoId)
    for task in todo_list.tasks:
        if(task.isCompleted):
            delete_one(TodoItem, task.id)
            print("here")
    return redirect(url_for('todoList.get_todo'))


@todoList.route('<int:todoId>/items/<int:itemId>/toggle', methods=['PATCH'])
def get_home(todoId,  itemId):
    item = get_one(TodoItem, itemId)
    item.isCompleted = not item.isCompleted
    db.session.commit()
    return {
        "message": "succcess"
    }

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=0.9">


    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title>Todo List App</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="add-list-form">
  <form class="add-todo" method="post">
    {{ form.name(class_='todolist-input', placeholder="Enter new list", value="", maxlength=128) }}
    {{ form.submit  }}
  </form>
</div>

<div class="container">

  <div class="todos-container">
  {%for todo in todos%}
  <a class='card-class'href="/todolist/{{ todo.id }}">  
    <div class="card">
 
        <p class="count">{{ todo.tasks|length }}</p >
        <div class="card-text">
          <p>{{ todo.name }}</p>
        </div>
        <div class="card-stats">
          <div class="dunder"></div>
          <p class="list-button">Get Started</p>
        </div>

  </div>
  </a>
  {% endfor %}
  </div>
</div>
{% endblock %}

app/templates/todolist.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="todo-container">
        <div class="todo-header">
            <a href="/" class="home">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="2em" height="2em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24">
                    <path d="M12 2C6.486 2 2 6.486 2 12s4.486 10 10 10s10-4.486 10-10S17.514 2 12 2zm5 11h-5v4l-5-5l5-5v4h5v2z"/></svg></a>
            <h3 class="todo-name">{{todo.name}}</h3>
            <div class="_header-dunder"></div>
        </div>
        <ol class="todo-items">
            {%for item in todo.tasks %}
                   <li class="item" id="{{ item.id }}">
                       <div class="_item-dunder"></div>
                       <span class="task">{{item.task}}</span>
                        <div class="complete">
                       {% if item.isCompleted == True %}
                        <svg xmlns="http://www.w3.org/2000/svg" class="check-icon" id="check-icon{{item.id}}" 
                        width="24" height="24" viewBox="0 0 24 24"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"/></svg>
                        {%endif%} 
                        </div>
                    </li> 
            {%endfor%}
            <div class="item-input">   
                <form method="post">
                    {{ form.task(class_='todo-input', placeholder="Enter new task", value="", maxlength=128) }}
                    {{ form.submit}}
                    </form>
            </div>
            <input type="submit" id="clear" value="clear complete">
            <div class="delete">
               
                <form method="post" action="{{url_for('main.delete_todo', todoid=todo.id)}}">
                    <input type="submit" class="delete-button" value="delete list">
                </form>
            </div>
        </ol>  
    </div>

 
</div>
<script>


let todoId = {{ todo.id }};
todoId = todoId.toString();
items = document.getElementsByClassName("item")
clearBtn = document.getElementById("clear")

for(let item of items){
    item.addEventListener("mouseover", function(){
        let svg_class = "check-icon" + item.id
        svgItem = document.getElementById(svg_class)
        if (svgItem){
            svgItem.classList.add("hover-check")
        }

    })
    item.addEventListener("mouseout", function(){
        let svg_class = "check-icon" + item.id
        svgItem = document.getElementById(svg_class)
        if(svgItem){
            svgItem.classList.remove("hover-check")
            svgItem.classList.add("default-check")
        }
  
    })

    item.addEventListener("click", function(){
        const Http = new XMLHttpRequest();
        Http.onreadystatechange = function(){
            if(Http.readyState === 4){
                document.location.reload(true)
            }
        }
        const url = todoId + '/items/' + this.id + '/toggle'
        Http.open("PATCH", url)
        Http.send()
    })
}

clearBtn.addEventListener("click", function(){
    console.log("click")
    const Http = new XMLHttpRequest();
    Http.onreadystatechange = function(){
        if(Http.readyState === 4){
            document.location.reload(true)
        }
    }      
    const url = todoId + '/clearComplete'
    Http.open("POST", url)
    Http.send()
})



</script>
{% endblock %}